version: "3"
services:
  smapshot:
    build: .
    image: swissartresearx/bso-smapshot
    container_name: ${PROJECT_NAME}
    restart: always
    volumes:
      - ./data:/data
      - ./mapping:/mapping
      - ./pipeline:/pipeline
      - ./.env:/dotenv/.env