### Configuration
version: '3'

vars:
  # Output folder for XML files
  outputFolder: ../data/xml

  # Attribute to use for naming files
  filenameKey: original_id

  # Platform configuration for ingest
  endpoint: http://platform:8080/rdf-graph-store
  graph: https://resource.swissartresearch.net/graph/smapshot
  username: admin
  password: admin