# https://taskfile.dev

version: '3'

vars:
  GENERATOR_POLICY: /mapping/generator-policy.xml

tasks:
  run:
    desc: Run entire pipeline
    cmds:
    - task: retrieve-data
    - task: prepare-mapping
    - task: perform-mapping

  ingest:
    vars:
      GRAPH: https://resource.swissartresearch.net/graph/smapshot
      ENDPOINT: http://platform:8080/rdf-graph-store
      USERNAME: admin
      PASSWORD: admin
      TTL_FOLDER: /data/ttl
    cmds:
      - |
        GRAPHURLENCODE=$(echo $(echo "{{.GRAPH}}" | sed "s/:/%3A/g") | sed "s/\//%2F/g")
        curl -v -u {{.USERNAME}}:{{.PASSWORD}} -X DELETE {{.ENDPOINT}}?graph=$GRAPHURLENCODE
        for f in $(ls {{.TTL_FOLDER}}/*.ttl); do
          curl -v -u {{.USERNAME}}:{{.PASSWORD}} -X PUT -H "Content-Type: text/turtle" --data-binary "@$f" {{.ENDPOINT}}?graph=$GRAPHURLENCODE
        done

  retrieve-data:
    desc: Download the detailed data for all validated images in the SARI/BSO collection into the `/data` folder. The data is converted to XML for later mapping using the X3ML Mapping Engine.
    cmds:
      - python retrieve-smapshot-data.py

  prepare-mapping:
    desc: Compare the retrieved XML files with the mapped TTL files and copy all unconverted XML files to a temporary folder.
    vars:
      INPUT_FOLDER: /data/xml
      OUTPUT_FOLDER: /data/ttl
      TEMP_FOLDER: /data/temp
    cmds:
      - rm -rf {{.TEMP_FOLDER}}
      - mkdir -p {{.TEMP_FOLDER}}
      - |
        MAPPED_FILES=$(ls -1 {{.OUTPUT_FOLDER}} | sed s/.ttl//g)
        for l in $(ls -1 {{.INPUT_FOLDER}} | sed s/.xml//g); do 
          if [[ ! $MAPPED_FILES =~ (^|[[:space:]])$l($|[[:space:]]) ]]; then
            cp "{{.INPUT_FOLDER}}/$l.xml" "{{.TEMP_FOLDER}}/$l.xml"
          fi
        done

  perform-mapping:
    desc: Map Smapshot XML data in the temporary folder to CIDOC/RDF
    vars:
      INPUT_FOLDER: /data/temp
      OUTPUT_FOLDER: /data/ttl
      MAPPING_FILE: /mapping/mapping-smapshot.x3ml
      BATCHSIZE: 1
    status:
      - test {{.INPUT_FOLDER}}/*.xml
    sources:
      - /data/temp/*.xml
      - /mapping/mapping-smapshot.x3ml
    generates:
      - /data/ttl/*.ttl
    cmds:
      - bash /pipeline/performMapping.sh -i {{.INPUT_FOLDER}} -o {{.OUTPUT_FOLDER}} -m {{.MAPPING_FILE}} -g {{.GENERATOR_POLICY}} -b {{.BATCHSIZE}}
